version: '3.8'

services:
  webhook-interface:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n-webhook-interface
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      - ./logs:/var/log/nginx
    labels:
      # Coolify labels for automatic proxy configuration
      - "coolify.managed=true"
      - "coolify.version=3.0.0"
      - "traefik.enable=true"
      - "traefik.http.routers.webhook-interface.rule=Host(`${COOLIFY_FQDN}`)"
      - "traefik.http.routers.webhook-interface.entrypoints=websecure"
      - "traefik.http.routers.webhook-interface.tls.certresolver=letsencrypt"
      - "traefik.http.services.webhook-interface.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  logs:
