# .github/workflows/deploy.yml
name: 🚀 Deploy to Coolify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: 🧪 Test Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t n8n-webhook-interface:test .

      - name: Test Docker container
        run: |
          docker run -d --name test-container -p 8080:80 n8n-webhook-interface:test
          sleep 10
          curl -f http://localhost:8080 || exit 1
          docker stop test-container
          docker rm test-container

  deploy:
    name: 🚀 Deploy to Coolify
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Coolify
        run: |
          echo "🚀 Triggering Coolify deployment..."
          curl -X GET "${{ secrets.COOLIFY_WEBHOOK_URL }}" \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}" \
            -w "HTTP Status: %{http_code}\n" \
            --fail-with-body

      - name: Deployment Status
        run: |
          echo "✅ Deployment triggered successfully!"
          echo "🔗 Check your Coolify dashboard for deployment progress"
          echo "📱 Application will be available at: ${{ secrets.APP_URL }}"

  notify:
    name: 📢 Notify Status
    runs-on: ubuntu-latest
    needs: [test, deploy]
    if: always()
    
    steps:
      - name: Success Notification
        if: needs.deploy.result == 'success'
        run: |
          echo "🎉 Deployment completed successfully!"
          
      - name: Failure Notification  
        if: needs.deploy.result == 'failure' || needs.test.result == 'failure'
        run: |
          echo "❌ Deployment failed. Check the logs above."
          exit 1
